version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/pricing.auvis.com
hooks:
  BeforeInstall:
    - location: deploy_hooks/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy_hooks/after.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deploy_hooks/verify_service.sh
      runas: root
      timeout: 300
      runas: root